spring.application.name=email-writer-sb
spring.config.import=optional:file:.env[.properties]

gemini.api.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}
gemini.api.key=${GEMINI_KEY:}